### ISSUE TITLE
'List index out of range' bei Seed 41

### ISSUE THREAD

**Issue by ChristophScn** [AbdBarho/Pandemie#3]
Wenn man Seed 41 mit eurer 'example.py' Implementierung spielt bekommt man noch folgende Exception ;-)
```
File "example.py", line 164, in index
  chosenPathogen = pickPathogen( pathogenList , amountOfPathogensList )
File "example.py", line 83, in pickPathogen
  return pathogenArr[0]
```

**Comment by AbdBarho** [comment]
Danke sehr für das Feedback!
Der Bug wurde [hier](https://github.com/AbdBarho/Pandemie/commit/e04a3302f622f124b933f7efa1d2ae7a07b40ef3) gefixt.

Sollten wir die korrigierte Version per Email nachreichen?

**Comment by ChristophScn** [comment]
Keine Ahnung, ich bin auch nur ein Teilnehmer. Die Abgabe ist bis zum 19.01., also sollte eine Nachreichung denke ich kein Problem sein.
